apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipes-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipes-database
  template:
    metadata:
      labels:
        app: recipes-database
    spec:
      containers:
      - name: recipes-database
        image: carl0222/recipes_database_amd64:latest
        # Add any necessary environment variables or volume mounts here

# You might also want to define a Service for your database if you need to access it externally.
# The specifics of this depend on your database system.
