version: '3'

services:
  backend:
    container_name: backend
    build: .
    ports:
      - "5002:5002"
    depends_on:
      - db
  db:
    container_name: db
    image: carl0222/recipes_database:latest
    ports:
      - "3306:3306"
    restart: always
      
    volumes:
      - db-data:/var/lib/mysql
  
  frontend:
    container_name: frontend
    image: carl0222/recipes
    ports:
      - "8080:80"
    restart: always
  

volumes:
  db-data:
